### ISSUE TITLE
Question about installing RUNEtags on Ubuntu 18.04

### ISSUE THREAD

**Issue by sunglyoungKim** [artursg/RUNEtag#4]
Hello,
I have installed all dependencies and I can run cmake build.

However, when I try to compile the source code I got this errors
compilation terminated.
CMakeFiles/RUNETag.dir/build.make:206: recipe for target 'CMakeFiles/RUNETag.dir/markerdetector.cpp.o' failed
make[2]: *** [CMakeFiles/RUNETag.dir/markerdetector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/RUNETag.dir/ellipserefine.cpp.o
In file included from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/digitalmarkermodel.hpp:41:0,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/markerdetected.hpp:36,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/markerpose.hpp:34,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/auxrenderer.hpp:34,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/auxrenderer.cpp:29:
/home/sunglyoung/Tags/RUNEtag/RUNETag/include/coding.h:31:9: fatal error: NTL/lzz_pE.h: No such file or directory
 #include<NTL/lzz_pE.h>
         ^~~~~~~~~~~~~~
compilation terminated.
In file included from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/digitalmarkermodel.hpp:41:0,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/markerdetected.hpp:36,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/markerpose.hpp:34,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/markerpose.cpp:30:
/home/sunglyoung/Tags/RUNEtag/RUNETag/include/coding.h:31:9: fatal error: NTL/lzz_pE.h: No such file or directory
 #include<NTL/lzz_pE.h>
         ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/RUNETag.dir/build.make:86: recipe for target 'CMakeFiles/RUNETag.dir/auxrenderer.cpp.o' failed
make[2]: *** [CMakeFiles/RUNETag.dir/auxrenderer.cpp.o] Error 1
CMakeFiles/RUNETag.dir/build.make:230: recipe for target 'CMakeFiles/RUNETag.dir/markerpose.cpp.o' failed
make[2]: *** [CMakeFiles/RUNETag.dir/markerpose.cpp.o] Error 1
In file included from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/digitalmarkermodel.hpp:41:0,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/markerdetected.hpp:36,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/include/slotfitter.hpp:35,
                 from /home/sunglyoung/Tags/RUNEtag/RUNETag/slotfitter.cpp:30:
/home/sunglyoung/Tags/RUNEtag/RUNETag/include/coding.h:31:9: fatal error: NTL/lzz_pE.h: No such file or directory
 #include<NTL/lzz_pE.h>
         ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/RUNETag.dir/build.make:254: recipe for target 'CMakeFiles/RUNETag.dir/slotfitter.cpp.o' failed
make[2]: *** [CMakeFiles/RUNETag.dir/slotfitter.cpp.o] Error 1
/home/sunglyoung/Tags/RUNEtag/RUNETag/ellipserefine.cpp:33:10: fatal error: highgui.h: No such file or directory
 #include <highgui.h>
          ^~~~~~~~~~~
compilation terminated.
CMakeFiles/RUNETag.dir/build.make:278: recipe for target 'CMakeFiles/RUNETag.dir/ellipserefine.cpp.o' failed
make[2]: *** [CMakeFiles/RUNETag.dir/ellipserefine.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/RUNETag.dir/all' failed
make[1]: *** [CMakeFiles/RUNETag.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any idea how I can debug it?

**Comment by artursg** [comment]
Error like `#include<NTL/lzz_pE.h>` indicates that ntl library is not installed. Try installing `libntl-dev` and compiling again.

**Comment by sunglyoungKim** [comment]
Thank you for the quick response!!
I have installed the library and the error is gone.

Thank you so much!

Btw, may I know your recommendation OpenCV version for RUNEtags?  I am using OpenCV 4.3.0.

I am debugging small variable changes but it seems like using your recommendation would be more reliable. 

One more question is; do you plan to update your code to compatible with OpenCV4.0?

**Comment by artursg** [comment]
In my opinion the version of OpenCV wouldn't affect anything. 
Although i am not one of the original authors, I would like to adapt it for modern systems (in my spare time).

**Comment by sunglyoungKim** [comment]
I have successfully install RUNEtag with opencv 3.7.10. Thank you so much!
